# Generated by Django 5.0.4 on 2024-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='dateOrderd',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='transaction_id',
            new_name='transactionId',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='dateAdded',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_added',
            new_name='dateAdded',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
