# Generated by Django 5.0.4 on 2024-04-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='static/images/placeholder.png', null=True, upload_to=''),
        ),
    ]
